# Now Presenting: LastMinerStanding Multiarena System
LastMinerStanding:
  # Do not change this value:
  config: 2
  
  # Do you want the arena to be enabled?
  enabled: false
  # Minimum amount of players required for the game to start.
  MinPlayers: 3
  # Maximum amount of players being able to join.
  MaxPlayers: 16
  # From here on, you can create the join signs:
  JoinSigns:
    # Do you want joinsigns to be enabled? (Support for Multiworld servers only!)
    enabled: true
    # Syntax: "WORLD;X-coordinate;Y-coordinate;Z-coordinate" | Example: "world;127;64;-25"
    # (If no Fallback is provided, players will be kicked when the game ends.)
    Locations:
      - "world;0;64;0"
      - "world;0;64;1"
      - "world;0;64;2"
  # Lobby Location
  LobbyLocation:
    World: "world"
    X: 0
    Y: 64
    Z: 0
  # Spectator Respawn Location
  Spectator:
    enabled: false
    Location:
      World: "world"
      X: 0
      Y: 64
      Z: 0
  # Where do you want players to be teleported to when the game is over?
  Fallback:
    Bungeecord:
      enabled: false
      Server: "lobbyserver"
    Multiworld:
      enabled: false
      World: "lobbyworld"
  # Airdrop Manager
  Airdrops:
    # Do you want Airdrops to be enabled in this arena?
    enabled: true
    # What material should the chest be (can be any block you wish)?
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
    # PLEASE NOTE: Some blocks can't let beacon light through!
    ChestMaterial: ENDER_CHEST
    # How long should the delay between two airdrops be (in seconds)?
    DelaysBetweenAirdrops: 60
    # How many items do you want to have per chest (maximum amount)?
    MaxItemsPerChest: 3
    # Beacon Light System
    BeaconLight:
      # Do you want the Beacon Light System to be enabled?
      enabled: true
      # What colors do you want the beacon light to have in the states?
      # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/DyeColor.html
      # Use "NULL" as color to turn the light off.
      Colors:
        # Color, when the chest hasn't been opened yet:
        not_opened_yet: GREEN
        # Color, when the chest has been opened already:
        opened_already: WHITE
  # MOTD Manager
  MOTD:
    # Do you want to enable the MOTD Manager (recommended for standaloneservers ONLY!)
    enabled: false
    # Gamestate Manager
    # Placeholders: 
    #  {players} - Amount of players online in this arena
    #  {alives} - Amount of players that are alive in this arena (ingame only!)
    #  {countdown} - Current countdown (lobby only!)
    Gamephases:
      # Lobby Phase
      Lobby: "&6LMS &7> &aLobby, {players} players waiting"
      # Ingame Phase
      Ingame: "&6LMS &7> &eIngame, {alives} players alive"
      # GameOver Phase
      GameOver: "&6LMS &7> &cRestarting"
