# LastMinerStanding Configuration File
LastMinerStanding:
  # Do not change this value:
  config: 14
  # Do you want this plugin to be on a standalone server system?
  # Standalone means, that this is the only gametype on the server
  # If true: The plugin will be the only gametype on the server
  # If false: You use a MultiWorld System on your Server (Multiverse etc.)
  standaloneServer: true
  # Do you want to disable the feature that LastMinerStanding checks for any missing configuration options in your files?
  # This feature can help you to detect and fix any issues due to missing configuration options.
  # # For further explanation, read here: https://github.com/ItzMace/LastMinerStanding-DEV/issues/227
  disableCheckForMissingConfigOptions: false
  # Do you want to disable metrics?
  # # Metrics are usefull to collect data to improve the general experience with LastMinerStanding.
  disableMetrics: false
  # Do you want to allow us to remove your idcounts.dat file in the world folder when the server restarts?
  # (Needed to fix the map overflow in the world directory)
  forceRemoveIdCounts: false
  # Do you want to execute the /reload command when the round is over?
  # NOTE: The server won't stop, it will just reload. This is not recommended, but you wished it to be added.
  doReloadAndNoShutdown: false
  # AAC: If you have issues using the parachute with AAC, please increase this value (recommended: 3).
  # (NOTE: This will disable the fly check for all LastMinerStanding players for the amount below in seconds)
  aacCompatibilityDelay: 0
  # Prevent the players to stomp wheat in the lobby world?
  PreventStomping: true
  # Do you want to prevent a player from joining when the game has already been started?
  PreventJoinAfterStart: false
  # General JoinSign Module
  JoinSigns:
    # Do you want the signs to be placed to the given locations by the plugin?
    # (LIMITED SUPPORT: Sometimes signs may break and lay as items on ground. Should be used for testing only!)
    autoSpawnSigns: false
    # General Syntax of Join Signs [PLACEHOLDERS: {players}, {maxplayers}, {state}, {timer}]
    Syntax:
      Line1: "&8[ &6LMS &8]"
      Line2: "&6{players} &8/ &6{maxplayers}"
      Line3: "{state}"
      Line4: "{timer} seconds"

  # MOTD Manager:
  # Placeholders:
  # {players} = amount of online players
  # {maxplayers} = amount of max players allowed
  # {minplayers} = amount of min players required to start
  # {countdown} = countdown until game starts
  MOTDsupport:
    # Do you want to enable custom MOTD support?
    enabled: false
    # MOTD for game state 'LOBBY'
    lobby: "&aLMS &7> &aLOBBY"
    # MOTD for game state 'INGAME'
    ingame: "&aLMS &7> &6INGAME"
    # MOTD for game state 'RESTARTING'
    restarting: "&aLMS &7> &cRESTARTING"

  # Performance Manager:
  PerformanceManager:
    # This will limit the amount of blocks that are placed at the same time.
    BlockPlacingQueue:
      enable: true
      # Amount of blocks to be placed every x ticks (= every tickInterval)
      batchSize: 1
      # Amount of ticks between block placing batches (20 ticks = 1 second)
      tickInterval: 5
      # Place blocks that are close to a player for improved gameplay experience.
      PriorityBlockPlacingToClosePlayers:
        enable: true
        # Range around a player where blocks are placed earlier.
        distanceToPlayer: 50
    # This will place all the chests when the world is being loaded (on server start)
    # (INFORMATION: This only works on STANDALONE SERVERS!)
    PlaceChestsOnServerStart:
      # Amount of blocks to be placed every x ticks (= every tickInterval)
      batchSize: 50
      # Amount of ticks between block placing batches (20 ticks = 1 second)
      tickInterval: 10

# Here you can edit gameplay relevant settings
Gameplay:
  # Minimum amount of players required for the game to start.
  MinPlayers: 3
  # Maximum amount of players being able to join.
  MaxPlayers: 16
  # Should hunger be enabled ingame?
  enableHunger: true
  # Do you want players to drop items on death?
  dropItemsOnDeath: true
  # Do you want to allow players to drop items from their inventory?
  dropItemsOutOfInventory: true
  # Do you want to enable players natural regeneration when the food bar is full enough?
  useNaturalRegeneration: false
  # Do you want to fully disallow breaking blocks in the lobby world?
  disallowBlockBreaksInLobbyWorld: true
  # How many HP should all players have max.? (Default: 20.0 = 10 Hearts)
  maxHealthModifier: 20.0
  
  # Parachute Manager
  ParachuteManager:
    # Do you want the parachute to be disabled? (Note: Players will fall out of the sky.)
    DisableParachute: false
    # Do you want the parachute to be visible? (This will spawn a chicken on the players head)
    VisibleParachute: true
    # Do you want to use Elytra-Flight for Spigot 1.9+? (Limited support if true!)
    ElytraFlight: false
    # Do you want to put the replaced chestplate of a player into his/ her inventory (if possible)?
    #  If false, the item will be saved internally and put as chestplate once the player lands.
    PlaceReplacedChestplateToInventory: true
    # Do you want the player to temporary disable the parachute by holding the 'sneak' key?
    SneakToDisable: true
    # Do you want to disable/ lock the parachute in the current round for players after they landed on the ground once?
    LockParachuteAfterOnGround: false
    # Settings for the movement of the player when a parachute is deployed.
    MovementSettings:
      # Fall speed multiplier, when there is a parachute deployed.
      FallSpeedMultiplier: 0.75
      # Fall speed multiplier, when there is a parachute deployed.
      DirectionSpeedMultiplier: 0.375
  
  # From here on, the Team engine starts:
  Teams:
    # This defines the size of one team. If solo, enter 1 (Default: 1)
    size: 1
    # Team-Selector Item
    Item:
      # Do you want players to be able to select their team using an item?
      enabled: true
      # Team-Selector Item
      Type: WATCH
      # Team-Selector Item
      Name: "&6Select Team"
    # Do you want Friendly Fire to be enabled?
    friendlyFire: false
    # Which Material should by bypassed by block break protection?
    TeamNames:
      # Do you want to generate team names by the player names in the team? (If false, the list underneath will be used)
      generateTeamNames: false
      # If false, the following team names will be picked:
      List:
        - "Alpha"
        - "Bravo"
        - "Charlie"
        - "Delta"
        - "Echo"
  
  # Custom Player Models (to prevent targetting or for special events)
  CustomPlayerModels:
    # Here you can control the skin of the players.
    Skins:
      # Do you want to enable the custom skin manager?
      disable: false
      # Information of the custom skin you want the players to have:
      # # THIS WILL BE ADDED IN THE NEXT UPDATE.
      # # The current implementation is for debugging/ testing.
  
  # Here you can manage which blocks players should be able to break during ingame:
  BlockBreak:
    AllowAll: true
    # Which Material should by bypassed by block break protection?
    SAND:
      # Which Material should be dropped when the block has been destroyed?
      Drop: SAND
      # How much Exp should be drop when the block has been destroyed?
      Exp: 0
    GRASS:
      # Which Material should be dropped when the block has been destroyed?
      Drop: DIRT
      # How much Exp should be drop when the block has been destroyed?
      Exp: 0
    DIRT:
      # Which Material should be dropped when the block has been destroyed?
      Drop: DIRT
      # How much Exp should be drop when the block has been destroyed?
      Exp: 0
    STONE:
      # Which Material should be dropped when the block has been destroyed?
      Drop: STONE
      # How much Exp should be drop when the block has been destroyed?
      Exp: 0
      
  # Here you can manage which blocks players should be able to place during ingame
  # If you want to disable BlockPlacing, enter "- AIR" as Blockplace item!
  BlockPlace:
    - "*"

  # Blood System
  # Player starts bleeding when getting damaged
  # User needs to use Bandages to stop bleeding
  BloodSystem:
    # Do you wish to enable the blood system?
    enabled: true
    # How much blood should the user have when the round starts?
    blood: 5.0
    # How much more blood should the user loose when getting damaged?
    # Placeholders: {damage}, {finaldamage}
    looseBloodFormula: "{finaldamage}/150.0"
    # What Material should be Bandages made of?
    material: "PAPER"
    # Should Bandages be automatically renamed?
    renameBandages: true
    # What should be the new name?
    newBandageName: "&7Bandage"
    # How much L/s should a bandage reduce when used
    bandageEffectivity: 5.0
    # BLACKLISTED DAMAGE CAUSES (https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html)
    # You can add any damage cause here that wil not increase the bleeding of a player.
    # Possible examples: DROWNING, STARVATION, FALL
    blacklistedDamagecause:
      - DROWNING
      - STARVATION
      - FALL

  # JumpPad System
  # Can be used to boost players into the air when they step on pressure plates.
  JumpPad:
    # Do you wish to enable the JumpPad system? (If false, this will overwrite the following options)
    enabled: true
    # Do you wish to enable the JumpPad system in the waiting lobby?
    enabled_in_lobby: true
    # What material should be used for JumpPads (default: STONE_PLATE)?
    material: "STONE_PLATE"
    # What should the push-distance be?
    push_distance: 3.5
    # What should the push-height be?
    push_height: 1.0

  # Backpack System
  # Can be used to give players additional inventory space.
  Backpack:
    # Do you wish to enable the Backpack system? (If false, this will overwrite the following options)
    enabled: true
    # Should the content of the backpack be bound to the player? (If false, the backpack-content is bound to the explicit item)
    content_bound_to_player: true
    # What do you want the title of the backpack-inventory to be?
    inventory_title: "&6Backpack"
    # How many slots do you want the backpack to have in size? (Default: 9)
    storage_size: 9
    # The backpack will be opened when right-clicking the following item.
    item:
      # What material should be used for Backpacks (default: LEATHER)?
      material: "LEATHER"
      # What item name should be used for Backpacks?
      name: "&6Backpack"
      # Do you want the item to be enchanted (using enchantment 'Durability')?
      is_enchanted: true

  # Specific Round Phase Settings
  Phases:
    # Change Lobby Phase specific settings
    Lobby:
      # To which time should the countdown be reset when
      # there are not enough players to start (in Seconds)
      Timer: 210
      # Sould we shorten the wait time when the server is full?
      InstantStartOnFull: true
      # Do you wish to see the countdown in your exp-bar?
      XPCountdown: false
    Ingame:
      # How long should the livegame be in total (+Warmup) (in Seconds)
      TotalTime: 1200
      # How long should the players have time to equip before
      # PVP will be enabled (in Seconds)
      Warmup: 60
      # Custom Command Executor
      Commands:
        # Do you want to dispatch commands when this game phase starts?
        enabled: false
        # Which command do you want to execute?
        commands:
          - "/examplecommand"
    GameEnd:
      # How long do you want the game end phase to be? (Default: 10)
      Time: 10
      # Custom Command Executor
      Commands:
        # Do you want to dispatch commands when this game phase starts?
        enabled: false
        # Only execute if there are any players who won?
        onlyOnWin: true
        # Which command do you want to execute?
        # Placeholders:
        # {winner_name} - The name(s) of the player(s) who won, otherwise 'null'
        # {winner_displayname} - The displayname(s) of the player(s) who won, otherwise 'null'
        # {winner_playerlistname} - The playerlistname(s) of the player(s) who won, otherwise 'null'
        commands:
          - "/examplecommand {winner_name}"
