# LastMinerStanding Configuration File
LastMinerStanding:
  # Do not change this value:
  config: 4

  # Which items do you want the players have in inventory on game start (Syntax: 'MATERIAL:AMOUNT' or 'MATERIAL'):
  StartItems:
        - COMPASS

  # Should the compass point to the next living player?
  UseCompassAsPointer: true

  # Here you can manage the item spawns:
  # If you turn multiple entries to true, the system will select a random spawn type
  ItemSpawns:
    # Do you want to spawn items in Chests?
    SpawnInChests:
        # Do you want to spawn items in Chests?
        Enable: true
        # How many Items should be in one chest?
        Amount: 5
    # Do you want to spawn items with Armor Stands?
    SpawnInArmorStands: false
    # Do you want to simply drop the items?
    # NOTICE: These dropped items won't respawn!
    SpawnDropItems: false

  # Weight Settings for Items
  Weight:
    # Enable the weight system to prevent players from taking too many items
    enabled: true
    # Maximal amount of weights a player can hold
    MaximumWeight: 100
    # Default weight of items picked up ingame (if NOT declared below)
    DefaultWeight: 0
    
  # From here on, you can customize your crackshot item support:
  CrackShotItems:
    # Do you want to ignore LastMinerStanding items and only use CrackShot items instead?
    # If this is set to false, CrackShot items will be added to the pool first (by chance)
    # and the rest of the free percentages will be filled with Items below (if total chance above 100)
    # Note: If CrackShot is NOT loaded, this option will be set to false
    useCrackShotItemsOnly: true
    Items:
      # IMPORTANT: Use your configured items name as item here (this is the default CS config):
      # Weight >> Defines the weight of the items due to the weight system above
      # Chance >> Defines the spawn chance of the items in the world on game start
      Gauss:
        Weight: 10
        Chance: 5
      Carbine:
        Weight: 10
        Chance: 5
      Deagle:
        Weight: 6
        Chance: 5
      Bazooka:
        Weight: 20
        Chance: 5
      Python:
        Weight: 10
        Chance: 5
      Riotshield:
        Weight: 10
        Chance: 5
      Olympia:
        Weight: 10
        Chance: 5
      Hunting:
        Weight: 13
        Chance: 5
      Type95:
        Weight: 10
        Chance: 5
      AK-47:
        Weight: 10
        Chance: 5

  # Custom declareration of items that can be found in game
  # Weight >> Defines the weight of the items due to the weight system above
  # Chance >> Defines the spawn chance of the items in the world on game start
  Items:
    # Tools, Materials & Other Items
    POTION:
      Weight: 0
      Chance: 0
    STICK:
      Weight: 0
      Chance: 0
    COMPASS:
      Weight: 0
      Chance: 0
    FISHING_ROD:
      Weight: 3
      Chance: 5
    BOAT:
      Weight: 45
      Chance: 0
    PAPER:
      Weight: 7
      Chance: 6
    STONE:
      Weight: 3
      Chance: 0
    IRON_INGOT:
      Weight: 3
      Chance: 0
    GOLD_INGOT:
      Weight: 2
      Chance: 0
    LEATHER:
      Weight: 2
      Chance: 0
    # ELYTRA for 1.9+ only. For 1.8 -> RAILS
    ELYTRA:
      Weight: 20
      Chance: 0
    RAILS:
      Weight: 20
      Chance: 0
    # Food
    COOKED_BEEF:
      Weight: 1
      Chance: 7
    GOLDEN_APPLE:
      Weight: 8
      Chance: 5
    # BOW & ARROW
    BOW:
      Weight: 8
      Chance: 5
    ARROW:
      Weight: 1
      Chance: 5
    # SWORDS
    IRON_SWORD:
      Weight: 9
      Chance: 3
    STONE_SWORD:
      Weight: 7
      Chance: 5
    WOOD_SWORD:
      Weight: 4
      Chance: 5
    GOLD_SWORD:
      Weight: 3
      Chance: 5
    # IRON ARMOR
    IRON_HELMET:
      Weight: 5
      Chance: 3
    IRON_CHESTPLATE:
      Weight: 50
      Chance: 1
    IRON_LEGGINGS:
      Weight: 30
      Chance: 2
    IRON_BOOTS:
      Weight: 6
      Chance: 3
    # CHAINMAIL ARMOR
    CHAINMAIL_HELMET:
      Weight: 4
      Chance: 5
    CHAINMAIL_CHESTPLATE:
      Weight: 22
      Chance: 5
    CHAINMAIL_LEGGINGS:
      Weight: 12
      Chance: 5
    CHAINMAIL_BOOTS:
      Weight: 4
      Chance: 5
    # LEATHER ARMOR
    LEATHER_HELMET:
      Weight: 2
      Chance: 5
    LEATHER_CHESTPLATE:
      Weight: 6
      Chance: 5
    LEATHER_LEGGINGS:
      Weight: 4
      Chance: 5
    LEATHER_BOOTS:
      Weight: 2
      Chance: 5
