# LastMinerStanding Configuration File
LastMinerStanding:
  # Do not change this value:
  config: 4
  
  # Custom declareration of messages being send ingame
  # (Chat) Messages can be edited here:
  # Placeholders:
  # {name}					|		Displays the Name of a specific player (depends on context)
  # {team_name}				|		Displays the Teamname of a specific team (depends on context)
  # {displayame}				|		Displays the Displayname of a specific player (depends on context)
  # {playerlistname}			|		Displays the Playerlistname of a specific player (depends on context)
  # {killer_name}				|		Displays the Name of a specific killer (depends on context)
  # {killer_displayame}		|		Displays the Displayname of a specific killer (depends on context)
  # {killer_playerlistname}	|		Displays the Playerlistname of a specific killer (depends on context)
  # {br}						|		Linebreak (Starts a new line)
  # {minplayers}				|		Shows the amount of players that are required to start the game
  # {lobbytimer}				|		Shows the current lobby timer (in seconds) until game starts
  Messages:
    # The Prefix will be printed in front of every message
    prefix: "&a&lLMS &8> "
    # This message will be send on join [Placeholders: {name}, {displayname}, {playerlistname}]
    join_message: "&a» &7 &6{displayname} &7has joined the game."
    # This message will be send on quit [Placeholders: {name}, {displayname}, {playerlistname}]
    quit_message: "&c« &7 &6{displayname} &7has left the game."
    # This message will be send when there are not enough players to start the game
    lobby_notEnoughPlayers: "&cThe game needs at least {minplayers} players to start. {br}&7The countdown has been reset."
    # This message will be send when there are not enough players to start the game
    lobby_countdown: "&7The game starts in &6{lobbytimer} &7seconds!"
    # This message will be send when all Items have been placed in the world
    ingame_placeItems: "&aThere were &e{items} items &ahidden in the world."
    # This message will be send when the warmup countdown expired and PVP is enabled
    ingame_pvpEnable: "&4&lPVP has now been enabled"
    # This message will be send when the player lands on the ground
    ingame_flyEnd: "&a&lGood luck. You can now search for items."
    # This message will be send when the time runs out and no winner is given
    end_gameTimedOut: "&cThe game has end!{br}No winner could be determined!"
    # This message will be send when the server is about to shut down
    end_restarting: "&7The server restarts in &e{timer} second(s)"
    # This message will be send when a player dies without other players damage
    player_death: "&7The player &a{name} &7has died.&7"
    # This message will be send when a player gets killed by a player
    player_killed: "&7The player &a{name} &7was killed by &a{killer_name} &7"
    # This message will be send when all players left the game and there is no winner
    noWinnerLeft: "&cThere are no more players. The server will restart now."
    # This message will be send when a player won LastMinerStanding
    playerWon: "&e&lThe player &6&l{name}&e&l has won LastMinerStanding"
    # This message will be send when a team won LastMinerStanding
    teamWon: "&e&lThe team &6&l{team_name}&e&l has won LastMinerStanding"
    # This message will be send when player don't have enough permission
    missingPermission: "&cYou don't have enough permission to access this."
    # This message will be send when a player breaks a block that is not allowed to be destroyed
    # (Leave empty to disable this message)
    breakBlockDisallowed: "&cYou are not allowed to break this block."
    # This message will be send when a player gets spectator
    spectator: "&cYou are now spectator!"
    # This message will be send when a player selects a player to spectate
    spectatingPlayer: "&bYou are now spectating: {name}"
    # This message will be send when a player selects a player to spectate but this player can not be found
    spectatingPlayerFailed: "&cWe can't find this player. Please try again."
    # This will be send to a player when he/she uses the /start command
    gameStarted: "&aYou started the game..."
    # This message will be send when a player reached the maxmimum item weight allowed
    maxItemWeightReached: "&cYou have too many items in your inventory...{br}&cPlease drop some of them"
    # BloodSystem Messages:
    BloodSystem:
      # This message will be send when a player fully stopped the bleeding with using a bandage
      bleedingStopped: "&aYou're no longer bleeding."
      # This message will be send when a player is bleeding less after using a bandage
      bleedingDecreased: "&eYou're bleeding less after using a bandage."
      # This message will be send when a player fully stopped the bleeding and tries to use another bandage.
      notBleeding: "&aYou are not bleeding at the moment."
    # Safezone Messages:
    Safezone:
      # Actiobar Countdown:
      # Do you want the actionbar countdown to be enabled?:
      enableActionbarCountdown: true
      # What do you want the actionbar countdown to be? [Placeholder: {countdown}]:
      actiobarCountdownMessage: "&aThe border shrinks in &e{countdown} seconds"
    # Multiarena Messages:
    Multiarena:
      # What message should a player recieve when joining an arena? [Placeholder: {arena_name}]:
      joinArenaMessage: "&aYou have been connected to &l{arena_name}"
    # Team Messages:
    Teams:
      # What message should a player recieve when successfully joining a team? [Placeholder: {team_name}]:
      team_joined: "&aYou've joined &6{team_name}."
      # What message should a player recieve when joining a team that is already full? [Placeholder: {team_name}]:
      team_full: "&cSorry, but the team you wanted to join is already full."
      # This message will be send when a player attacks a player who is part of the same team
      # (Leave empty to disable this message)
      friendlyFireWarning: "&cFRIENDLY FIRE! FRIENDLY FIRE!{br}&cStop hitting your teammates."
    # Airdrop Messages:
    Airdrop:
      # What message do you want to be displayed when an airdrop is deployed? [Placeholder: {x}, {z}]
      # (Note: If you want to disable this message, leave it empty.)
      deployMessage: "&6Airdrop has reached its target.{br}&6Get it at &aX: {x} &6and &aZ: {z}"
