# World Configuration File for LastMinerStanding
World:
  # Do you want this map to be enabled?
  enabled: true
  # This are general environment settings
  Environment:
    # This time will be set on game start (like /time <time> command)
    Time: 4
    # Do you want to hold the time on the value above or you want to let the sun go as default?
    HoldTime: false
    # Do you want to disable rain?
    DisableRain: true
  # This are the default worldborder settings
  Worldborder:
    # Where do you want to set the worldborder center?
    Center:
      X: 531
      Z: -720
    # Which radius do you want to have the worldborder
    Radius: 450
  # This are the item spawn location (areas)
  # YOU ARE FREE TO SET AS MANY SPAWN LOCATION AS YOU WISH TO. MAKE THEN WITH INCREASING IDs (Spawn0, Spawn1, Spawn2...)
  ItemSpawn:
    # This is Spawn Area #0:
    Spawn0:
      # Do you want to have this spawn location enabled?
      enabled: true
      # How many items do you want to spawn in this area (eg. amount of Chests)
      AmountOfItems: 12
      # Do you want Items to be spawned in caves?
      AllowCaves: false
      # This is the start location of the item spawn area:
      From:
        X: 419
        Y: 64
        Z: -735
      # This is the end location of the item spawn area:
      To:
        X: 719
        Y: 76
        Z: -698
    # This is Spawn Area #1:
    Spawn1:
      # Do you want to have this spawn location enabled?
      enabled: true
      # How many items do you want to spawn in this area (eg. amount of Chests)
      AmountOfItems: 3
      # Do you want Items to be spawned in caves?
      AllowCaves: false
      # This is the start location of the item spawn area:
      From:
        X: 399
        Y: 63
        Z: -838
      # This is the end location of the item spawn area:
      To:
        X: 421
        Y: 104
        Z: -803
